* Things Left to Build
** Data View
Data can be visualized in an analogous way to the model. Conditional data histograms can be constructed etc.  
* Model Communication (Server/Client)
** Must correctly alert when query can be built 
There are remaining issues. For some reason the check does not automatically alert us when the model isready for query. Also, when arrows are disconnected, the model is not reset ...that has to simply be implimented (have not yet done that). Once the alert works correctly, I can build the querying system in a similar way as the switcher ...multiple queries can be shown in the model view marked with Q1, Q2, ...Qn.
* Data/Betting View Communication
Here, a bet must be popped off the moment a new data point comes in and points must be allocated. We can then post winnings to the facebook profile etc. 
* The Tutorial
* View Minimization into small views analogous to the mini-hists. 
* Some modifications from the conversation with Ernesto
** Only one binary betting variable (except for the Monty tutorial)
All other variables should only be used for prediction
** Bits instead of binary bets
Players should observe what other people bit, but betting should be more as a prediction market on binary variables.
** Bits can be killed
** Give everyone 1000 initial points  
** Constant time (non-dependent on action)
People should know ahead of time when they can expect a new data point to show up. 
** mini-hists and views are important for seeing everything together
** in the data view have summary statistics available. 
